// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc2337.RobotProject2016.subsystems;

import org.usfirst.frc2337.RobotProject2016.RobotMap;
import org.usfirst.frc2337.RobotProject2016.commands.*;

import edu.wpi.first.wpilibj.Solenoid;
import edu.wpi.first.wpilibj.command.Subsystem;


/**
 *
 */
public class LED extends Subsystem {

	
	private final Solenoid GRIPCameraLed = RobotMap.ledGRIPCamera;
	private final Solenoid targetingLight = RobotMap.targetLightLight;
   
    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        setDefaultCommand(new led_DoNothing());

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
    }
    /**
     * Turn on GRIP Camera Led with full power
     */
    public void ledOn_GRIPCamera() {
    	GRIPCameraLed.set(true);
    }
    /**
     * Turn off GRIP Camera Led with no power
     */
    public void ledOff_GRIPCamera() {
    	GRIPCameraLed.set(false);
    }
    /**
     * Find the status of GRIP Camera Led
     */
    public void ledStatus_GRIPCamera() {
    	GRIPCameraLed.get();
    }
    public void lightOn(){
    	targetingLight.set(true);
    }
    public void lightOff(){
    	targetingLight.set(false);
    }
}

