// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc2337.RobotProject2016.subsystems;

import org.usfirst.frc2337.RobotProject2016.RobotMap;
import edu.wpi.first.wpilibj.DoubleSolenoid;
import edu.wpi.first.wpilibj.DoubleSolenoid.Value;
import edu.wpi.first.wpilibj.command.Subsystem;


/**
 *
 */
public class PowerTakeOff extends Subsystem {

    private final DoubleSolenoid ptoSolenoid = RobotMap.powerTakeOffptoSolenoid;


    public void initDefaultCommand() {


        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
    }
    
    public void LiftOn(Value ptoState) {
    	ptoSolenoid.set(ptoState);
    }
    
    public void LiftOn(){
    	ptoSolenoid.set(DoubleSolenoid.Value.kForward);
    }
    
    public void LiftOff(){
    	ptoSolenoid.set(DoubleSolenoid.Value.kReverse);
    }
    
    public Value LiftStatus(){
    	return ptoSolenoid.get();
    }
}

