// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc2337.RobotProject2016.subsystems;

import org.usfirst.frc2337.RobotProject2016.RobotMap;
import org.usfirst.frc2337.RobotProject2016.commands.*;

import edu.wpi.first.wpilibj.DoubleSolenoid;
import edu.wpi.first.wpilibj.Solenoid;
import edu.wpi.first.wpilibj.command.Subsystem;


/**
 *
 */
public class Scaler extends Subsystem {

  
    private final DoubleSolenoid scalerAirActuator = RobotMap.grapplingHookRelease;
    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public void initDefaultCommand() {
        setDefaultCommand(new scaler_DoNothing());

    }
    
    /**
     * Extend the scaler arm
     */
    public void pinOut(){
    	scalerAirActuator.set(DoubleSolenoid.Value.kForward);
    }
    /**
     * Retract the scaler arm 
     */
    public void pinIn(){
    	scalerAirActuator.set(DoubleSolenoid.Value.kReverse);
    }
    /**
     * get the status of pneumatic pin
     * @return
     */
   // public Value getPinStatus() {
    //	return scalerAirActuator.get();
    //}
    
    
}

